### ISSUE TITLE
Can't run sample code

### ISSUE THREAD

**Issue by francisco1844** [arriqaaq/skiplist#1]
I ran 
 go get -u github.com/arriqaaq/skiplist

Copied the sample code from the [readme](https://github.com/arriqaaq/skiplist) and get errors when I try to go run the file
```
# command-line-arguments
./t.go:18:12: undefined: list
./t.go:19:2: undefined: assert
./t.go:19:15: undefined: t

```

This is the code I ran.. which is identical to readme
### package main

import "github.com/arriqaaq/skiplist"

type kv struct{k,v string}

func main() {

    // Set (accepts any value)
    n := skiplist.New()
	val := []byte("test_val")

	n.Set("ec", val)
	n.Set("dc", 123)
	n.Set("ac", val)

    // Get
    node:= list.Get("ec")
	assert.Equal(t, val, node.Value())

    // Delete
	n.Delete("dc")
}

**Comment by arriqaaq** [comment]
There is a small typo, but apart from that you'd just have to import "github.com/stretchr/testify/assert"

Alternatively you can remove that assert line to avoid the import

**Comment by arriqaaq** [comment]
updated

**Comment by francisco1844** [comment]
Trying latest code from readme

```
go get -u github.com/arriqaaq/skiplist
go get github.com/stretchr/testify/assert
go run sl.go 
./sl.go:22:18: undefined: t

```

Also, this part doesn't seem like it is neede either
`type kv struct{k,v string}`

**Comment by arriqaaq** [comment]
Yeah, avoiding the unnecessary assert, fixed it, thanks for the issue

```go
package main

import (
	"fmt"

	"github.com/arriqaaq/skiplist"
)

func main() {

	// Set (accepts any value)
	val := "test_val"

	n := skiplist.New()
	n.Set("ec", val)
	n.Set("dc", 123)
	n.Set("ac", val)

	// Get
	node := n.Get("ec")
	fmt.Println("value: ", node.Value())

	// Delete
	n.Delete("dc")
}

```

**Comment by arriqaaq** [comment]
Tested it

**Comment by francisco1844** [comment]
Latest code works. Thanks.
